//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev.gmeister.unsighted.randomeister.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dev.gmeister.unsighted.randomeister.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weapon,gun,jump	CavesMinecartBarrierPuzzle_SecretForkChest,CavesPond_BattleChestCavesPond_DustChestCavesNestRoom_DustChestCavesNestRoom_KeyChestCavesCorridor_ChestSewersCentralRoom_EasyChest2AquariumWestElevator_BlockPuzzleChestAquariumExternalCombatRoom_FrostbiteChestMuseumLabyrinth_DustChest,MuseumMoonDeviceCorridor_TopChest,MuseumKeyRoomF2_Chest,MuseumKeyRoom_MuseumKey1,DowntownFinalPuzzle_KeyChest,DowntownIndustrialZoneEntrance_GhoulBattleChest
        ///weapon,gun,rock,jump	SuburbsRailsDowntownElevator_DustChes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicLogic {
            get {
                return ResourceManager.GetString("BasicLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key	1000	2000
        ///MetalCog	150	300
        ///WoodenBranch	30	60
        ///MetalScrap	30	60
        ///IronBar	150	300
        ///Wires	150	300
        ///IceCrystal	150	300
        ///EletricCoil	150	300
        ///FlammableOil	150	300
        ///MeteorDust	1000	2000
        ///EngineOil	30	60
        ///Fuse	150	300
        ///MeteorShard	8000	12000
        ///JumpBoots	1000	2000
        ///RocketBoots	0	0
        ///Syringe	1000	2000
        ///DisposableSyringe	150	300
        ///Research	1000	2000
        ///DarkEssence	1000	2000
        ///PetBerry	30	60
        ///Bolts1	25	25
        ///Bolts2	100	100
        ///Bolts3	500	500
        ///Bolts4	1500	1500
        ///TreasurePhotos	1000	2000
        ///Shovel	1000	2000
        ///GoldenShovel	1000	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemPrices {
            get {
                return ResourceManager.GetString("ItemPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacksmith2NPC	BlasterBlueprint,SpinnerBlueprint,Hookshot1Blueprint,AutomaticBlasterBlueprint,ShotgunBlueprint,FlamethrowerBlueprint,IcethrowerBlueprint,GranadeLauncherBlueprint,IceGranadeBlueprint,GranadeShotgunBlueprint,FlamebladeBlueprint,WarAxeBlueprint,FireAxeBlueprint,IronStarBlueprint,IceStarBlueprint,FireStarBlueprint,ThunderStarBlueprint,JumpBootsBlueprint	3	6
        ///GeneralShopNPC	Key,MetalCog,WoodenBranch,MetalScrap,IronBar,Wires,IceCrystal,EletricCoil,FlammableOil,EngineOil,Fuse,DisposableSyringe,Dark [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NPCShops {
            get {
                return ResourceManager.GetString("NPCShops", resourceCulture);
            }
        }
    }
}
